import { describe, expect, it } from 'vitest'
import { HEADER_LINE, HEADER_MARKER, isOwned } from './header.js'

describe('header', () => {
  it('HEADER_MARKER is the expected string', () => {
    expect(HEADER_MARKER).toBe('@generated by crossmod')
  })

  it('HEADER_LINE starts with the marker', () => {
    expect(HEADER_LINE.startsWith(`// ${HEADER_MARKER}`)).toBe(true)
  })

  it('HEADER_LINE ends with double newline', () => {
    expect(HEADER_LINE.endsWith('\n\n')).toBe(true)
  })
})

describe('isOwned', () => {
  it('returns true for content starting with header', () => {
    expect(isOwned(`// ${HEADER_MARKER} — DO NOT EDIT\n\nexport * from './foo'`)).toBe(true)
  })

  it('returns false for hand-written content', () => {
    expect(isOwned("export * from './foo'")).toBe(false)
  })

  it('returns false for empty content', () => {
    expect(isOwned('')).toBe(false)
  })

  it('returns false for similar but not exact marker', () => {
    expect(isOwned('// @generated by something-else')).toBe(false)
  })
})
