export const HEADER_MARKER = '@generated by madmod'
export const HEADER_LINE = `// ${HEADER_MARKER} — DO NOT EDIT\n\n`
export const isOwned = (content: string): boolean => content.startsWith(`// ${HEADER_MARKER}`)
